# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ac9cebfa3bcb2503b73923d5337a787fb382bf12027eed351f53ad00cd162187a57eb3b887cc210dbcaf689b9a5912feb74c67003f82d7ec8078c6c203b847

test:
  secret_key_base: b037076f29f2d5da1b0f1d47ad75be3d9dc3c032e5cb9a1ebb4c4d2425577adf099990744326a817635d2302e367995d368005bdad9f4680179984bb07c87c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
